IpRegisterCountLimit: 2
IpCountLimit: 2
LimitChineseID: true
MinLengthID: 2
MaxLengthID: 15
BeforeLoginNoDamage: true
ReenterInterval: 60
AfterLoginBack: true
CanTpSpawnLocation: true
CommandWhiteList:
  - /(?i)l(ogin)?(\z| .*)
  - /(?i)reg(ister)?(\z| .*)
  - /(?i)resetpassword?(\z| .*)
  - /(?i)repw?(\z| .*)
  - /(?i)worldedit cui
AutoKick: 120
DeathStateQuitRecordLocation: true
# 允许跳过登录的玩家名字前缀列表 (例如：["Admin", "VIP"])
SkipLoginPrefixes: []
